name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'addon.json'
          prop_path: 'version'
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'Avix-PokiSDK-${{steps.version.outputs.prop}}.c3addon'
        exclusions: '*.git* /*node_modules/* .editorconfig'